language: go
go:
  - "1.10.x"
dist: trusty
before_script:
  - "go get -u golang.org/x/lint/golint"
  - "go get -u github.com/golang/dep/cmd/dep"
  # setting fake configuration.
  "kubectl config set-credentials myself --username=admin --password=secret"
  "kubectl config set-cluster local-server --server=http://localhost:8080"
  "kubectl config set-context default-context --cluster=local-server --user=myself"
  "kubectl config use-context default-context"
  "kubectl config set contexts.default-context.namespace the-right-prefix"
  "kubectl config view"
script:
  - "make fmtcheck"
  - "make vet"
  - "make lint"
  - "make ensure"
  - "make build"
  - "make test"
