language: go
go:
  - "1.10.x"
dist: trusty
sudo: required
before_script:
  - "go get -u golang.org/x/lint/golint"
  - "go get -u github.com/golang/dep/cmd/dep"
  - "go get github.com/kisielk/errcheck"
  - "sudo mkdir -p /var/run/secrets/kubernetes.io/serviceaccount && sudo touch /var/run/secrets/kubernetes.io/serviceaccount/token"
script:
  - "make fmtcheck"
  - "make vet"
  - "make lint"
  - "make errcheck"
  - "make ensure"
  - "make build"
  - "KUBERNETES_SERVICE_HOST=localhost KUBERNETES_SERVICE_PORT=8000 make test"
