language: go
go:
  - "1.10.x"
dist: trusty
before_script:
  - "go get -u golang.org/x/lint/golint"
script:
  - "make fmtcheck"
  - "make vet"
  - "make lint"
  - "make ensure"
  - "make build"
  - "make test"
